name: gnotus

services:
  backend:
    image: docker.io/merlinz01/gnotus-backend:latest
    restart: unless-stopped
    init: true
    depends_on:
      - search
    environment:
      - GNOTUS_CONFIG_FILE=/app/config.yml
      - GNOTUS_BASE_URL=${GNOTUS_BASE_URL:-http://localhost}
      - GNOTUS_DB_URL=sqlite:/data/gnotus.db
      - GNOTUS_UPLOADS_DIR=/data/uploads
      - GNOTUS_LOG_LEVEL=INFO
      - GNOTUS_SESSION_SECRET_KEY=${SECRET_KEY}
      - GNOTUS_CSRF_SECRET_KEY=${SECRET_KEY}
      - GNOTUS_MEILISEARCH_URL=http://search:7700
      - GNOTUS_MEILISEARCH_API_KEY=${SECRET_KEY}
    volumes:
      - ./data:/data
      - ./config.yml:/app/config.yml
      - ./icon.svg:/app/icon.svg

  search:
    image: getmeili/meilisearch:v1.15
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${SECRET_KEY}
    volumes:
      - ./data/meilisearch:/data.ms

  frontend:
    image: docker.io/merlinz01/gnotus-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    environment:
      - API_ADDRESS=http://backend:8080
      - CADDY_EMAIL=${CADDY_EMAIL}
      - CADDY_DOMAIN=${CADDY_DOMAIN:-"http://localhost"}
