
FROM debian:trixie-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
WORKDIR /venv
COPY ./pyproject.toml ./uv.lock ./
RUN uv sync --link-mode=copy
WORKDIR /app
EXPOSE 8000
CMD ["/venv/.venv/bin/fastapi", "dev", \
    "--host", "0.0.0.0", \
    "--port", "8000", \
    "--reload"]
