name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@16feee727cbdc83b6a014e6cc26fec4a79bcf30c # v2.2.0

      - name: Build dev image
        run: docker compose -f compose.dev.yml build backend

      - name: Run tests
        run: docker compose -f compose.dev.yml run --rm backend /venv/.venv/bin/pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: backend
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: merlinz01/gnotus-backend:latest
          cache-from: type=registry,ref=merlinz01/gnotus-backend:latest
          cache-to: type=inline

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@16feee727cbdc83b6a014e6cc26fec4a79bcf30c # v2.2.0

      - name: Run tests
        run: >
          docker compose -f compose.dev.yml run --rm --build frontend
          bash -c "npm install --frozen --ignore-scripts && npm run test run"

      - name: Log in to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: frontend
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: merlinz01/gnotus-frontend:latest
          cache-from: type=registry,ref=merlinz01/gnotus-frontend:latest
          cache-to: type=inline
