name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build dev image
        run: docker compose -f compose.dev.yml build backend

      - name: Run tests
        run: docker compose -f compose.dev.yml run --rm backend /venv/.venv/bin/pytest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: merlinz01/gnotus-backend:latest
          cache-from: type=registry,ref=merlinz01/gnotus-backend:latest
          cache-to: type=inline

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build dev image
        run: docker compose -f compose.dev.yml build frontend

      - name: Run tests
        run: docker compose -f compose.dev.yml run --rm frontend npm run test run

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: merlinz01/gnotus-frontend:latest
          cache-from: type=registry,ref=merlinz01/gnotus-frontend:latest
          cache-to: type=inline
