name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build dev image
        run: docker compose -f compose.dev.yml build backend

      - name: Run tests
        run: docker compose -f compose.dev.yml run --rm backend /venv/.venv/bin/pytest

      - name: Build backend image
        run: docker build -t merlinz01/gnotus-backend:latest backend

      - name: Save backend image as artifact
        run: docker save merlinz01/gnotus-backend:latest -o gnotus-backend-image.tar

      - name: Upload backend image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gnotus-backend-image
          path: gnotus-backend-image.tar

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build dev image
        run: docker compose -f compose.dev.yml build frontend

      - name: Run tests
        run: docker compose -f compose.dev.yml run --rm frontend npm run test run

      - name: Build frontend image
        run: docker build -t merlinz01/gnotus-frontend:latest frontend

      - name: Save frontend image as artifact
        run: docker save merlinz01/gnotus-frontend:latest -o gnotus-frontend-image.tar

      - name: Upload frontend image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gnotus-frontend-image
          path: gnotus-frontend-image.tar

  publish-images:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Download backend image artifact
        uses: actions/download-artifact@v4
        with:
          name: gnotus-backend-image

      - name: Load backend image
        run: docker load -i gnotus-backend-image.tar

      - name: Download frontend image artifact
        uses: actions/download-artifact@v4
        with:
          name: gnotus-frontend-image

      - name: Load frontend image
        run: docker load -i gnotus-frontend-image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish backend image
        run: docker push merlinz01/gnotus-backend:latest

      - name: Publish frontend image
        run: docker push merlinz01/gnotus-frontend:latest
